class Sounds {
  static Map<String, String> sounds = {
    "ahem": "Ahem.mp3",
    "ahem 2": "Ahem_2.mp3",
    "ahem 3": "Ahem_3.mp3",
    "ajimaru kazoo": "ajimaru_kazoo.mp3",
    "(ASMR)Ahhhh": "ASMR_Ahhhh.mp3",
    "(ASMR)yabai crowing": "ASMR_yabai_crow_sound.mp3",
    "(ASMR)yabai dying ": "ASMR_yabai_dying_sounds.mp3",
    "assemble": "assemble.mp3",
    "BBQ": "BBQ.mp3",
    "bebek": "bebek.mp3",
    "begging": "begging.mp3",
    "cat sounds": "cat_sounds.mp3",
    "chubax3": "chubax3.mp3",
    "cough_1": "cough_1.mp3",
    "engine sound": "engine_sound.mp3",
    "(evil) shuba": "evil_shuba.mp3",
    "hazukashii": "hazukashii.mp3",
    "here we go": "here_we_go.mp3",
    "hi honey": "hi_honey.mp3",
    "hiyaaa": "hiyaaa.mp3",
    "humming bgm": "humming_bgm.mp3",
    "I love cabbage x3": "i_love_cabbage_x3.mp3",
    "I want to nap": "i_want_to_nap.mp3",
    "INNNN": "INNNN.mp3",
    "itai itee itai": "itai_itee_itai.mp3",
    "jakajakajanjan": "jakajakajanjan.mp3",
    "kaiken": "kaiken.mp3",
    "KITAAAA": "KITAAAA.mp3",
    "koi": "koi.mp3",
    "kon x4": "kon_x4.mp3",
    "konpeko": "Konpeko.mp3",
    "ku nyan": "Ku_nyan.mp3",
    "lets party": "lets_party.mp3",
    "low energy shuba": "low_energy_shuba.mp3",
    "mama": "mama.mp3",
    "mesu shuba": "mesu_shuba.mp3",
    "morning shuba": "morning_shuba.mp3",
    "nnnaaaa na na": "nnnaaaa_na_na.mp3",
    "oi": "oi.mp3",
    "okay distant": "okay_distant.mp3",
    "oppe sugoi": "oppe_sugoi.mp3",
    "ora x3": "ora_x3.mp3",
    "ora x3 shuba x3": "ora_x3_shuba_x3.mp3",
    "oshiri puri puri": "oshiri_puri_puri.mp3",
    "oyasumi asmr": "oyasumi_asmr.mp3",
    "prr": "prr.mp3",
    "quackquack": "quackquack.mp3",
    "satifaction": "satifaction.mp3",
    "scream baka": "scream_baka.mp3",
    "secret": "secret.mp3",
    "shuba": "shuba.mp3",
    "shuba neck snap": "shuba_neck_snap.mp3",
    "shubaba yawn": "shubaba_yawn.mp3",
    "shubax4": "shubax4.mp3",
    "shushushu x3": "shushushu_x3.mp3",
    "shushushushu": "shushushushu.mp3",
    "spaciba": "spaciba.mp3",
    "subaru is #1": "subaru_is_number_1.mp3",
    "UN": "UN.mp3",
    "yabai distant": "yabai_distant.mp3",
    "yada": "yada.mp3",
    "yawn": "yawn.mp3",
    "(distant)yoisho": "yoisho_distant.mp3",
  };
}
